//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pluspoint.Message {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewNewIssueMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewNewIssueMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pluspoint.Message.ViewNewIssueMessage", typeof(ViewNewIssueMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   作成済みカードの可能性があります、新しいカードを挿入して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewIssue_ErrorMessage001 {
            get {
                return ResourceManager.GetString("NewIssue_ErrorMessage001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ただいまカード作成処理中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewIssue_ErrorMessage002 {
            get {
                return ResourceManager.GetString("NewIssue_ErrorMessage002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カードの新規作成が完了しました。
        ///お客様へカードをお渡ししてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewIssue_ErrorMessage003 {
            get {
                return ResourceManager.GetString("NewIssue_ErrorMessage003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規発行 - 確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewTitle_NewIssue_Check {
            get {
                return ResourceManager.GetString("ViewTitle_NewIssue_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規発行 - カード作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewTitle_NewIssue_CreateCard {
            get {
                return ResourceManager.GetString("ViewTitle_NewIssue_CreateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規発行 - 入力１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewTitle_NewIssue_Input1 {
            get {
                return ResourceManager.GetString("ViewTitle_NewIssue_Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規発行 - 入力２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewTitle_NewIssue_Input2 {
            get {
                return ResourceManager.GetString("ViewTitle_NewIssue_Input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規発行 - 入力３ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewTitle_NewIssue_Input3 {
            get {
                return ResourceManager.GetString("ViewTitle_NewIssue_Input3", resourceCulture);
            }
        }
    }
}
