#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pluspoint.Database.LinqSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pluspointDB")]
	public partial class APPLI_HISTORYDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertAPPLI_HISTORY(APPLI_HISTORY instance);
    partial void UpdateAPPLI_HISTORY(APPLI_HISTORY instance);
    partial void DeleteAPPLI_HISTORY(APPLI_HISTORY instance);
    #endregion
		
		public APPLI_HISTORYDataContext() : 
				base(global::pluspoint.Properties.Settings.Default.pluspointDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public APPLI_HISTORYDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public APPLI_HISTORYDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public APPLI_HISTORYDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public APPLI_HISTORYDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<APPLI_HISTORY> APPLI_HISTORY
		{
			get
			{
				return this.GetTable<APPLI_HISTORY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.APPLI_HISTORY")]
	public partial class APPLI_HISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _card_no;
		
		private System.Nullable<System.DateTime> _use_datetime;
		
		private System.Nullable<int> _card_shop_no;
		
		private string _user_name;
		
		private System.Nullable<int> _operation_type;
		
		private System.Nullable<decimal> _total_amount;
		
		private System.Nullable<decimal> _prepaid;
		
		private System.Nullable<decimal> _point;
		
		private System.Nullable<decimal> _other1;
		
		private System.Nullable<decimal> _other2;
		
		private System.Nullable<decimal> _other3;
		
		private System.Nullable<decimal> _other4_credit;
		
		private System.Nullable<decimal> _cash;
		
		private System.Nullable<decimal> _added_point;
		
		private System.Nullable<decimal> _card_point;
		
		private System.Nullable<decimal> _card_prepaid;
		
		private System.Nullable<System.DateTime> _pointcard_history_get_datetime;
		
		private System.Nullable<int> _pointcard_history_line_number;
		
		private System.Nullable<decimal> _card_point_before;
		
		private System.Nullable<decimal> _card_prepaid_before;
		
		private System.Nullable<bool> _UPLOAD_FLG;
		
		private System.Nullable<System.DateTime> _UPLOAD_DATE;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncard_noChanging(int value);
    partial void Oncard_noChanged();
    partial void Onuse_datetimeChanging(System.Nullable<System.DateTime> value);
    partial void Onuse_datetimeChanged();
    partial void Oncard_shop_noChanging(System.Nullable<int> value);
    partial void Oncard_shop_noChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onoperation_typeChanging(System.Nullable<int> value);
    partial void Onoperation_typeChanged();
    partial void Ontotal_amountChanging(System.Nullable<decimal> value);
    partial void Ontotal_amountChanged();
    partial void OnprepaidChanging(System.Nullable<decimal> value);
    partial void OnprepaidChanged();
    partial void OnpointChanging(System.Nullable<decimal> value);
    partial void OnpointChanged();
    partial void Onother1Changing(System.Nullable<decimal> value);
    partial void Onother1Changed();
    partial void Onother2Changing(System.Nullable<decimal> value);
    partial void Onother2Changed();
    partial void Onother3Changing(System.Nullable<decimal> value);
    partial void Onother3Changed();
    partial void Onother4_creditChanging(System.Nullable<decimal> value);
    partial void Onother4_creditChanged();
    partial void OncashChanging(System.Nullable<decimal> value);
    partial void OncashChanged();
    partial void Onadded_pointChanging(System.Nullable<decimal> value);
    partial void Onadded_pointChanged();
    partial void Oncard_pointChanging(System.Nullable<decimal> value);
    partial void Oncard_pointChanged();
    partial void Oncard_prepaidChanging(System.Nullable<decimal> value);
    partial void Oncard_prepaidChanged();
    partial void Onpointcard_history_get_datetimeChanging(System.Nullable<System.DateTime> value);
    partial void Onpointcard_history_get_datetimeChanged();
    partial void Onpointcard_history_line_numberChanging(System.Nullable<int> value);
    partial void Onpointcard_history_line_numberChanged();
    partial void Oncard_point_beforeChanging(System.Nullable<decimal> value);
    partial void Oncard_point_beforeChanged();
    partial void Oncard_prepaid_beforeChanging(System.Nullable<decimal> value);
    partial void Oncard_prepaid_beforeChanged();
    partial void OnUPLOAD_FLGChanging(System.Nullable<bool> value);
    partial void OnUPLOAD_FLGChanged();
    partial void OnUPLOAD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPLOAD_DATEChanged();
    #endregion
		
		public APPLI_HISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_no", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int card_no
		{
			get
			{
				return this._card_no;
			}
			set
			{
				if ((this._card_no != value))
				{
					this.Oncard_noChanging(value);
					this.SendPropertyChanging();
					this._card_no = value;
					this.SendPropertyChanged("card_no");
					this.Oncard_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_use_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> use_datetime
		{
			get
			{
				return this._use_datetime;
			}
			set
			{
				if ((this._use_datetime != value))
				{
					this.Onuse_datetimeChanging(value);
					this.SendPropertyChanging();
					this._use_datetime = value;
					this.SendPropertyChanged("use_datetime");
					this.Onuse_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_shop_no", DbType="Int")]
		public System.Nullable<int> card_shop_no
		{
			get
			{
				return this._card_shop_no;
			}
			set
			{
				if ((this._card_shop_no != value))
				{
					this.Oncard_shop_noChanging(value);
					this.SendPropertyChanging();
					this._card_shop_no = value;
					this.SendPropertyChanged("card_shop_no");
					this.Oncard_shop_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation_type", DbType="Int")]
		public System.Nullable<int> operation_type
		{
			get
			{
				return this._operation_type;
			}
			set
			{
				if ((this._operation_type != value))
				{
					this.Onoperation_typeChanging(value);
					this.SendPropertyChanging();
					this._operation_type = value;
					this.SendPropertyChanged("operation_type");
					this.Onoperation_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_amount", DbType="Money")]
		public System.Nullable<decimal> total_amount
		{
			get
			{
				return this._total_amount;
			}
			set
			{
				if ((this._total_amount != value))
				{
					this.Ontotal_amountChanging(value);
					this.SendPropertyChanging();
					this._total_amount = value;
					this.SendPropertyChanged("total_amount");
					this.Ontotal_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prepaid", DbType="Money")]
		public System.Nullable<decimal> prepaid
		{
			get
			{
				return this._prepaid;
			}
			set
			{
				if ((this._prepaid != value))
				{
					this.OnprepaidChanging(value);
					this.SendPropertyChanging();
					this._prepaid = value;
					this.SendPropertyChanged("prepaid");
					this.OnprepaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_point", DbType="Money")]
		public System.Nullable<decimal> point
		{
			get
			{
				return this._point;
			}
			set
			{
				if ((this._point != value))
				{
					this.OnpointChanging(value);
					this.SendPropertyChanging();
					this._point = value;
					this.SendPropertyChanged("point");
					this.OnpointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other1", DbType="Money")]
		public System.Nullable<decimal> other1
		{
			get
			{
				return this._other1;
			}
			set
			{
				if ((this._other1 != value))
				{
					this.Onother1Changing(value);
					this.SendPropertyChanging();
					this._other1 = value;
					this.SendPropertyChanged("other1");
					this.Onother1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other2", DbType="Money")]
		public System.Nullable<decimal> other2
		{
			get
			{
				return this._other2;
			}
			set
			{
				if ((this._other2 != value))
				{
					this.Onother2Changing(value);
					this.SendPropertyChanging();
					this._other2 = value;
					this.SendPropertyChanged("other2");
					this.Onother2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other3", DbType="Money")]
		public System.Nullable<decimal> other3
		{
			get
			{
				return this._other3;
			}
			set
			{
				if ((this._other3 != value))
				{
					this.Onother3Changing(value);
					this.SendPropertyChanging();
					this._other3 = value;
					this.SendPropertyChanged("other3");
					this.Onother3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other4_credit", DbType="Money")]
		public System.Nullable<decimal> other4_credit
		{
			get
			{
				return this._other4_credit;
			}
			set
			{
				if ((this._other4_credit != value))
				{
					this.Onother4_creditChanging(value);
					this.SendPropertyChanging();
					this._other4_credit = value;
					this.SendPropertyChanged("other4_credit");
					this.Onother4_creditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cash", DbType="Money")]
		public System.Nullable<decimal> cash
		{
			get
			{
				return this._cash;
			}
			set
			{
				if ((this._cash != value))
				{
					this.OncashChanging(value);
					this.SendPropertyChanging();
					this._cash = value;
					this.SendPropertyChanged("cash");
					this.OncashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_added_point", DbType="Money")]
		public System.Nullable<decimal> added_point
		{
			get
			{
				return this._added_point;
			}
			set
			{
				if ((this._added_point != value))
				{
					this.Onadded_pointChanging(value);
					this.SendPropertyChanging();
					this._added_point = value;
					this.SendPropertyChanged("added_point");
					this.Onadded_pointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_point", DbType="Money")]
		public System.Nullable<decimal> card_point
		{
			get
			{
				return this._card_point;
			}
			set
			{
				if ((this._card_point != value))
				{
					this.Oncard_pointChanging(value);
					this.SendPropertyChanging();
					this._card_point = value;
					this.SendPropertyChanged("card_point");
					this.Oncard_pointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_prepaid", DbType="Money")]
		public System.Nullable<decimal> card_prepaid
		{
			get
			{
				return this._card_prepaid;
			}
			set
			{
				if ((this._card_prepaid != value))
				{
					this.Oncard_prepaidChanging(value);
					this.SendPropertyChanging();
					this._card_prepaid = value;
					this.SendPropertyChanged("card_prepaid");
					this.Oncard_prepaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pointcard_history_get_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> pointcard_history_get_datetime
		{
			get
			{
				return this._pointcard_history_get_datetime;
			}
			set
			{
				if ((this._pointcard_history_get_datetime != value))
				{
					this.Onpointcard_history_get_datetimeChanging(value);
					this.SendPropertyChanging();
					this._pointcard_history_get_datetime = value;
					this.SendPropertyChanged("pointcard_history_get_datetime");
					this.Onpointcard_history_get_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pointcard_history_line_number", DbType="Int")]
		public System.Nullable<int> pointcard_history_line_number
		{
			get
			{
				return this._pointcard_history_line_number;
			}
			set
			{
				if ((this._pointcard_history_line_number != value))
				{
					this.Onpointcard_history_line_numberChanging(value);
					this.SendPropertyChanging();
					this._pointcard_history_line_number = value;
					this.SendPropertyChanged("pointcard_history_line_number");
					this.Onpointcard_history_line_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_point_before", DbType="Money")]
		public System.Nullable<decimal> card_point_before
		{
			get
			{
				return this._card_point_before;
			}
			set
			{
				if ((this._card_point_before != value))
				{
					this.Oncard_point_beforeChanging(value);
					this.SendPropertyChanging();
					this._card_point_before = value;
					this.SendPropertyChanged("card_point_before");
					this.Oncard_point_beforeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_prepaid_before", DbType="Money")]
		public System.Nullable<decimal> card_prepaid_before
		{
			get
			{
				return this._card_prepaid_before;
			}
			set
			{
				if ((this._card_prepaid_before != value))
				{
					this.Oncard_prepaid_beforeChanging(value);
					this.SendPropertyChanging();
					this._card_prepaid_before = value;
					this.SendPropertyChanged("card_prepaid_before");
					this.Oncard_prepaid_beforeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_FLG", DbType="Bit")]
		public System.Nullable<bool> UPLOAD_FLG
		{
			get
			{
				return this._UPLOAD_FLG;
			}
			set
			{
				if ((this._UPLOAD_FLG != value))
				{
					this.OnUPLOAD_FLGChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_FLG = value;
					this.SendPropertyChanged("UPLOAD_FLG");
					this.OnUPLOAD_FLGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPLOAD_DATE
		{
			get
			{
				return this._UPLOAD_DATE;
			}
			set
			{
				if ((this._UPLOAD_DATE != value))
				{
					this.OnUPLOAD_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_DATE = value;
					this.SendPropertyChanged("UPLOAD_DATE");
					this.OnUPLOAD_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
