#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pluspoint.Database.LinqSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pluspointDB")]
	public partial class T_PCARD_LOGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertT_PCARD_LOG(T_PCARD_LOG instance);
    partial void UpdateT_PCARD_LOG(T_PCARD_LOG instance);
    partial void DeleteT_PCARD_LOG(T_PCARD_LOG instance);
    #endregion
		
		public T_PCARD_LOGDataContext() : 
				base(global::pluspoint.Properties.Settings.Default.pluspointDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public T_PCARD_LOGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T_PCARD_LOGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T_PCARD_LOGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public T_PCARD_LOGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_PCARD_LOG> T_PCARD_LOG
		{
			get
			{
				return this.GetTable<T_PCARD_LOG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_PCARD_LOG")]
	public partial class T_PCARD_LOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _LOG_DATE;
		
		private string _MSG_ID;
		
		private string _MSG;
		
		private string _DBS_STATUS;
		
		private string _DBS_CREATE_USER;
		
		private string _DBS_CREATE_DATE;
		
		private string _DBS_UPDATE_USER;
		
		private string _DBS_UPDATE_DATE;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOG_DATEChanging(System.DateTime value);
    partial void OnLOG_DATEChanged();
    partial void OnMSG_IDChanging(string value);
    partial void OnMSG_IDChanged();
    partial void OnMSGChanging(string value);
    partial void OnMSGChanged();
    partial void OnDBS_STATUSChanging(string value);
    partial void OnDBS_STATUSChanged();
    partial void OnDBS_CREATE_USERChanging(string value);
    partial void OnDBS_CREATE_USERChanged();
    partial void OnDBS_CREATE_DATEChanging(string value);
    partial void OnDBS_CREATE_DATEChanged();
    partial void OnDBS_UPDATE_USERChanging(string value);
    partial void OnDBS_UPDATE_USERChanged();
    partial void OnDBS_UPDATE_DATEChanging(string value);
    partial void OnDBS_UPDATE_DATEChanged();
    #endregion
		
		public T_PCARD_LOG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_DATE", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime LOG_DATE
		{
			get
			{
				return this._LOG_DATE;
			}
			set
			{
				if ((this._LOG_DATE != value))
				{
					this.OnLOG_DATEChanging(value);
					this.SendPropertyChanging();
					this._LOG_DATE = value;
					this.SendPropertyChanged("LOG_DATE");
					this.OnLOG_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSG_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MSG_ID
		{
			get
			{
				return this._MSG_ID;
			}
			set
			{
				if ((this._MSG_ID != value))
				{
					this.OnMSG_IDChanging(value);
					this.SendPropertyChanging();
					this._MSG_ID = value;
					this.SendPropertyChanged("MSG_ID");
					this.OnMSG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSG", DbType="NVarChar(MAX)")]
		public string MSG
		{
			get
			{
				return this._MSG;
			}
			set
			{
				if ((this._MSG != value))
				{
					this.OnMSGChanging(value);
					this.SendPropertyChanging();
					this._MSG = value;
					this.SendPropertyChanged("MSG");
					this.OnMSGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBS_STATUS", DbType="NVarChar(50)")]
		public string DBS_STATUS
		{
			get
			{
				return this._DBS_STATUS;
			}
			set
			{
				if ((this._DBS_STATUS != value))
				{
					this.OnDBS_STATUSChanging(value);
					this.SendPropertyChanging();
					this._DBS_STATUS = value;
					this.SendPropertyChanged("DBS_STATUS");
					this.OnDBS_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBS_CREATE_USER", DbType="NVarChar(MAX)")]
		public string DBS_CREATE_USER
		{
			get
			{
				return this._DBS_CREATE_USER;
			}
			set
			{
				if ((this._DBS_CREATE_USER != value))
				{
					this.OnDBS_CREATE_USERChanging(value);
					this.SendPropertyChanging();
					this._DBS_CREATE_USER = value;
					this.SendPropertyChanged("DBS_CREATE_USER");
					this.OnDBS_CREATE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBS_CREATE_DATE", DbType="NVarChar(50)")]
		public string DBS_CREATE_DATE
		{
			get
			{
				return this._DBS_CREATE_DATE;
			}
			set
			{
				if ((this._DBS_CREATE_DATE != value))
				{
					this.OnDBS_CREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._DBS_CREATE_DATE = value;
					this.SendPropertyChanged("DBS_CREATE_DATE");
					this.OnDBS_CREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBS_UPDATE_USER", DbType="NVarChar(MAX)")]
		public string DBS_UPDATE_USER
		{
			get
			{
				return this._DBS_UPDATE_USER;
			}
			set
			{
				if ((this._DBS_UPDATE_USER != value))
				{
					this.OnDBS_UPDATE_USERChanging(value);
					this.SendPropertyChanging();
					this._DBS_UPDATE_USER = value;
					this.SendPropertyChanged("DBS_UPDATE_USER");
					this.OnDBS_UPDATE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBS_UPDATE_DATE", DbType="NVarChar(50)")]
		public string DBS_UPDATE_DATE
		{
			get
			{
				return this._DBS_UPDATE_DATE;
			}
			set
			{
				if ((this._DBS_UPDATE_DATE != value))
				{
					this.OnDBS_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._DBS_UPDATE_DATE = value;
					this.SendPropertyChanged("DBS_UPDATE_DATE");
					this.OnDBS_UPDATE_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
